### ISSUE TITLE
Lyrics display using tags not working

### ISSUE THREAD

**Issue by ReK42** [kbuffington/Georgia#102]
I'm getting the following error when trying to display lyrics from tags. I have commented out the config as it recommended, and confirmed the contents of the tags look good. After commenting out the config and restarting foobar it worked for a couple of songs but then broke again and hasn't worked since.

![2021-05-16_08-07-03](https://user-images.githubusercontent.com/4775937/118427665-9d89f580-b682-11eb-8c34-e4c79452740b.png)

**Comment by kbuffington** [comment]
I'm pretty stumped here. This error only displays if attempting to read lyrics from tags and foobar returns a value of `"."`. Just a period. This is what happens when foobar is attempting to read a field that it considers a spam field (and so never caches). Commenting it out should prevent this problem from happening again.

Some things you could try:
- Close foobar, change the artist or album name in another program, reopen foobar and see if the lyrics show back. Then you can change them back in foobar and see if they "stick" when you want to play the song again
- You can always move the tag to another field. You have time stamps there so you could move them to `%synced lyrics%` or `%syncedlyrics%` (or `%unsyncedlyrics%` with no space). None of those are marked as field spam so they should just "work" as they're included by default in `title_format_strings.lyrics` in the config file.

Unfortunately there isn't anything I can do about this as it's entirely dependent on what value foobar returns to FSM (or FSM returns to the script... not 100% sure).
