### ISSUE TITLE
Georgia Crashes on Load

### ISSUE THREAD

**Issue by pmcdonough8133** [kbuffington/Georgia#116]
I have been using Georgia for a while now and just today, something changed and now Georgia won't load.  When opening foobar or right clicking and asking Georgia to reload, I get this error:
![image](https://user-images.githubusercontent.com/48228637/141474636-3e332ae9-3aa3-4003-ba44-5191c4d6df6f.png)
I have tried re-installing the latest update but no luck.  I didn't change anything between yesterday when it worked and today when it errors each and every time so I'm a little lost as to how to proceed.
After clicking either Stop or Continue, both lead to this error popping up:
Error for Stop
![image](https://user-images.githubusercontent.com/48228637/141475136-8f3c0829-4b46-4b55-ba51-82d093a45eab.png)
Error for Continue
![image](https://user-images.githubusercontent.com/48228637/141475493-06cb05ad-1daa-459c-bbaa-7feb0b93f9ad.png)

**Comment by kbuffington** [comment]
Okay, the Unresponsive script warning is not really an error. I've spent a ridiculous amount of time trying to make it so those don't popup, but it can happen depending on your media, how it's set up, how many playlists you have, etc. You should always just hit continue. To minimized that happening (and to see if somehow it's related to the actual crash), update the time limit time from 5 to 10 seconds:

![image](https://user-images.githubusercontent.com/2282004/141491869-d3d5a041-a499-4f9b-ac75-4a403434599e.png)


The error you're currently getting when you continue is very weird. "Method called before fb2k was initialized completely" is a new one to me. What happens if after things error if you right click on the main panel and reload the theme? I'm guessing it works properly at that point.

**Comment by kbuffington** [comment]
Another thing you should probably do is upgrade FSM from 1.4.1 to 1.5.2.

**Comment by kbuffington** [comment]
One other thing to try if the first two don't fix it, right click on the panel, select panel properties and make sure "Display playlist on Startup" is false.

![image](https://user-images.githubusercontent.com/2282004/141492684-75aa0d75-6bbd-424c-9a14-96308e063d04.png)

**Comment by pmcdonough8133** [comment]
Went through the steps, seems like updating FSM did the trick.  I will say that before I updated, the behavior I was noticing that any time I right clicked the panel and hit reload, it still got the error but if I was playing a track then right clicked the panel, it loaded up just fine.  Maybe that helps in future debugging, maybe not,  Either way thank you for your help as it is working smoothly once again.

**Comment by kbuffington** [comment]
Cool. I'm a little nervous that the problem has only been masked temporarily, but keep an eye out and I'll see if I can't figure out anything else from my end.
