### ISSUE TITLE
Track title font looks a little ugly compared to others

### ISSUE THREAD

**Issue by KatyLB** [kbuffington/Georgia#17]
I installed the fonts on installation fine (I did this a few updates ago, but I don't think the fonts changed?) and while most of the fonts are pretty (as you can see in the rest of the image), this one just looks a little bit more jagged. It's on Windows 10.

![image](https://user-images.githubusercontent.com/37089178/65899756-4c919480-e3ac-11e9-9eba-39b986782148.png)

**Comment by kbuffington** [comment]
Unfortunately, it's just a biproduct of using such a thin font for the title text. I double-checked the [code](https://github.com/kbuffington/Georgia/blob/master/js/georgia-main.js#L592) and you can see it's setting text hinting to ClearTypeGridFit which is the highest quality. You can play around with AntiAlias or AntiAliasGridFit and see if you like any of those values better, but I did a fair amount of squinting at this when first deciding on what to use and liked ClearTypeGridFit the best.

If it really bugs you, you can change [lines 54, 55, and 56](https://github.com/kbuffington/Georgia/blob/master/js/georgia-main.js#L54) to use `'HelveticaNeueLT Std Lt'` instead of `'HelveticaNeueLT Std Thin'`. That's the same font that "Roxy Recordings" uses below. I'll think about it and decide whether I want to make that change when in non-4K mode

**Comment by KatyLB** [comment]
Thanks for the reply. I tried the switch to see if I'd prefer it, but it still looks bad even with the other font. See below:

![image](https://user-images.githubusercontent.com/37089178/65923345-8086ad00-e3e0-11e9-8086-835e4a688f29.png)

I feel like it should look the same as the, as you said, "Roxy Recordings", and not as it does. Is it to do with text hinting, or another issue?

**Comment by kbuffington** [comment]
The text hinting is slightly different. I think everything else in the theme is currently using `AntiAlias`. I think the issue is just the larger font size stretches things out a little bit making it easier to see some of the aliasing in the middle of the S and the top of the O. Unfortunately I don't think there's anything I can really do to improve that as it's just how Windows GDI draws fonts.

**Comment by kbuffington** [comment]
Actually on further testing, I'm seeing a noticeable reduction in the aliasing (on my 4K TV) by switching to line 592 to be `gr.SetTextRenderingHint(TextRenderingHint.AntiAliasGridFit);` Tell me how that works for you.

**Comment by KatyLB** [comment]
Tried that and yes, it's a marked improvement! Here's the same track as the original screenshot with that change:

![image](https://user-images.githubusercontent.com/37089178/65992473-33114b00-e487-11e9-9300-705f752885ab.png)

**Comment by kbuffington** [comment]
Implemented this officially throughout the UI in v1.1.5.
