### ISSUE TITLE
Track title looks ugly compared to others (volume 2)

### ISSUE THREAD

**Issue by KatyLB** [kbuffington/Georgia#23]
Hi. I installed the updated theme and the result is as below:

![image](https://user-images.githubusercontent.com/37089178/67428918-01e3f080-f5d7-11e9-925c-cba85b6f8a86.png)

You had indicated when you closed the issue that you'd implemented the change on the track title but if anything it looks uglier than before here. I can't make the same changes as before though because now the lines you mentioned don't correspond to the same code.

Report is partly because you said you'd implemented it officially yet this doesn't seem to be the case, and partly to ask how I can make the necessary changes to get it pretty again. For the time being I've continued using the old version of the theme :)

**Comment by kbuffington** [comment]
I like the thinner font, and so it's the default used for the titles. I updated the TextHinting throughout the theme to improve how things look, but it seems you just don't like the thinner font period. Change lines 61-63 in georgia-main.js to reference `fontLight` instead of `fontThin` and it will be exactly as your custom version had it in v1.1.4.
