### ISSUE TITLE
Cover art potential bug in playlist view

### ISSUE THREAD

**Issue by Artins90** [kbuffington/Georgia#27]
I am not sure if this is strictly related to Georgia of if it's caused by other factors, I noticed that there is a line going across the last cover and song name in the playlist.
Resizing the window allows me to move this line up and down, this is on a 4K screen.
Line when placed in the last slot:
<img width="393" alt="Capture2" src="https://user-images.githubusercontent.com/28777957/74621548-b46b3080-513d-11ea-82ed-b95a6deb7d05.PNG">
No line on the cover when scrolling the same album 1 position up from the last position, the line moves to the track number 2 instead:
<img width="389" alt="Capture3" src="https://user-images.githubusercontent.com/28777957/74621582-c9e05a80-513d-11ea-867d-daad5ff2bd57.PNG">

It might be hard to see, here is a zoomed version:
<img width="677" alt="Capture3" src="https://user-images.githubusercontent.com/28777957/74621700-2774a700-513e-11ea-912c-3ab124d4030e.PNG">

**Comment by kbuffington** [comment]
Yeah, this is a bug in either foo_jscript_panel or GDI itself, dealing with gradients which contain alpha values. I have to draw a gradient from like RGBA(32,32,32,255) to RGBA(32,32,32,0), and sometimes the last line which should have 0 alpha somehow wraps to 255 alpha.

It has to do with the size of the gradient itself which means it's susceptible to screen resolution as well. It's been driving me nuts for years, because I can't fix it all the time. I might look into what's happening in foo_jscript_panel and see if I can create a fix.

**Comment by Artins90** [comment]
Thank you for looking into this.
It's not a huge issue and it's barely noticeable, you might want to give it less priority if you are working on something else.

**Comment by kbuffington** [comment]
Think this is now fixed in 1.1.7. Just had to change the orientation of the FillGradRect and the order of colors. Reopen if you're still having problems.
