### ISSUE TITLE
Force display of front cover when switching albums

### ISSUE THREAD

**Issue by ReK42** [kbuffington/Georgia#50]
Currently, when switching tracks the artwork is displayed in alphabetical order. This means when you start up a new album the first thing you see is back.jpg. It would be much better to show the front cover (front.jpg, cover.jpg, folder.jpg, etc) first, and then continue cycling artwork in alphabetical order.

**Comment by kbuffington** [comment]
I'm looking at the code, and I think I know what your issue is. Right now the code looks for folder.*, and cover.jpg first, and then looks for any .jpg/.png's it finds, then it looks for folder.jpg's in the parent directory.

If you are using front.jpg then it will just appear alphabetically, or if you use anything other than folder.* in the parent directory, items in the current directory will appear alphabetically.

I'll be fixing this in the next 2.0 version.

**Comment by kbuffington** [comment]
This should be fixed by default, and also configurable in new the 2.0.0-beta1.

**Comment by ReK42** [comment]
Confirmed fixed, thanks!
