### ISSUE TITLE
Possible issue with timeline

### ISSUE THREAD

**Issue by dwmartin0906** [kbuffington/Georgia#62]
I just noticed something odd with the timeline.  The current track shows 1 or more previous last played dates, as it should.  But when the track hits the 60 second mark, triggering a new played date, all previous dates are wiped out.  Also, the time displayed for the new date is six hours ahead of my local time.

**Comment by kbuffington** [comment]
Hmmm... this happens for every track you play? Do the old dates reappear if you start the song over again or is only the last played date shown?

You can debug this a little bit by adding: 
`{ "label": "Played Dates", "val": "[%played_times%]" },` to the metadataGrid in the config file and see if those dates are wiped at the 60 second mark. That'll help determine if it's an issue with the foo_enhanced_playcount component (possibly a corrupted metadb file) or the theme itself.

**Comment by kbuffington** [comment]
Also, when you say "time displayed is six hours ahead" is that if you mouse over the played bar in the timeline or where?

**Comment by dwmartin0906** [comment]
I've tried it on several tracks and it happens every time,  If I play another track, then replay the one with the issue, the other dates are still missing.  i am displaying the played times in the grid now and they are not being wiped out.  However, even if I play a new track, and before hitting the 60 second point, the most dates I see displayed on the timeline are 2.  But some of these tracks actually have several previous play dates which are correctly reflected in the play count and the displayed played times.  As for the incorrect time being displayed, yes, it is when I hover over the newly added timeline bar.  The corresponding grid played time, however, has the correct time.  I also noticed that although the grid Play Count is updated on the fly when the track hits the 60 second point, the Last Played date isn't updated until I play the track again.

**Comment by dwmartin0906** [comment]
Now that I can see all of the previous played times, I noticed that the pre-existing times in the timeline, before being wiped out, are also 6 hours ahead from what is stored in the foo_enhanced_playcount component.

**Comment by kbuffington** [comment]
Sorry, i gave you the wrong foo_playcount_enhanced property. Change `[%played_times%]` to `[%lastfm_played_times%]`. There will always only be two of the first but the 2nd should have 0 to N number of scrobbles.

The last played time doesn't _visually_ update as you play (which took more work than you'd think) because 80+% of the time (if your songs are 5 minutes+ long) it'd always be today's date, and I already know that I listened to it today 😀 

Can you let me know what timezone are you in? Presumably it's either GMT +6 or -6 hours.

You are running the theme in Windows and not under WINE or anything, right?

**Comment by dwmartin0906** [comment]
I'm using the latest version of Windows 10 and my time zone is CST.  But you have really confused me now.  You say when using %played_times% there will always only be two.  But I see more than two for many of my tracks, equal in number to the play count.  For %lastfm_played_times%, I see nothing, just empty brackets, which makes sense since I don't use LastFM for anything.  I don't even know what a scrobble is.  But I do have the foo_enhanced_playcount component installed.  Maybe I don't understand how the timeline works, but I'm sure that in the past I would see a bar for each date on which the track had been played, sometimes a bunch of them.  Has something changed?

**Comment by kbuffington** [comment]
Just ignore me. I don't know what I'm talking about and I got confused by your response. %played_times% was the correct value.

Yes you should see a bar on the time line for each played date (and thicker/darker bars if played multiple times on the same date). It sounded like from your original post that that is what you're seeing, until the song hits 60s when the previous bars on the timeline disappear.

The timeline code hasn't changed in the last 5 months, but I did refactor it early on in the rewrite for spidermonkey. If you used the theme in the pre-beta then nothing regarding the timeline has been altered since then. Everything works fine for me, and I'm in the same timezone so that rules out an issue that only works correctly in CST. Need to think about this a little more, as I'm not sure what else to test if %played_times% isn't missing any values for you.

**Comment by dwmartin0906** [comment]
Don't waste anymore time on this.  I went back to your untouched code and the timeline was working as expected.  Evidently I broke something when I retrofitted my changes.  I didn't touch any of the timeline code so I'm not sure just what I did.  I am so sorry for wasting your time on this.  Thank you very much for your help.

**Comment by kbuffington** [comment]
Whew! Just glad to know I didn't screw anything up!
