### ISSUE TITLE
Using wrong artwork

### ISSUE THREAD

**Issue by exful3** [kbuffington/Georgia#69]
I believe this is a bug with Georgia, but I can't be sure. When I play a song from a folder I make for the artist, it uses this artwork from another song. If I make a folder inside the "artist" folder for the song, it uses its own artwork again.
![bug](https://user-images.githubusercontent.com/9982507/105468665-d67a0680-5c5c-11eb-8336-266d5a86bd16.jpg)
![bug1](https://user-images.githubusercontent.com/9982507/105468666-d67a0680-5c5c-11eb-81de-d61d6aa04b85.jpg)
![bug2](https://user-images.githubusercontent.com/9982507/105468669-d7129d00-5c5c-11eb-94f4-c36dd2c0f992.jpg)
![bug3](https://user-images.githubusercontent.com/9982507/105468663-d5e17000-5c5c-11eb-82fa-abea7719be38.jpg)

EDIT;
By adding the artwork panel, I confirmed the problem is with from with Georgia, and not foobar, as it display the correct artwork.

**Comment by kbuffington** [comment]
This is very weird. Is the artwork embedded? I don't see any .jpgs so I'm assuming yes, although that wavves images is very pixelated which makes me think it might be a hidden image that Windows Media Player or something else downloaded.

Other possibilities. It could be a caching issue in which case moving it to a new folder would fix the problem because the path has changed. You could try moving it back and then restarting the theme which will clear the cache.

If you're using ColumnsUI you could also check to make sure you don't have any weird paths setup in the artwork tab.

**Comment by exful3** [comment]
Hey! Figured this one out! [https://www.howtogeek.com/howto/windows-vista/show-hidden-files-and-folders-in-windows-vista/](url) This helped me find a hidden "Folder.jpg" in the root that was causing the issue. Deleting it was the solution. Also, had to enable "Cycle Through Artwork" to keep the artwork from staying on a single image between songs!
