### ISSUE TITLE
Question/feature request about playlist sorting

### ISSUE THREAD

**Issue by ghost** [kbuffington/Georgia#85]
Is there not a way to change the playlist's default sorting query? There doesn't seem to be. For one example here, I often will have more than one issue of the same album, all tagged with the same album title, but also tagged appropriately with their respective catalog numbers and other release-specific information. Which, within Georgia, allows me to create a custom grouping query to account for this, but there doesn't seem to be a way to change the playlist's default sorting query in a similar manner, nullifying the usefulness of my grouping query, and making things even uglier than they were before without it.
There are other examples to merit custom default sorting queries, such as sorting by date, if you often like to add an artist's entire discography to the playlist etc, but separating different issues of the same album is what concerns me most.
Have I overlooked something here? If not, then could this ever be an option? I was quite excited about using Georgia up until this discovery.

**Comment by kbuffington** [comment]
So currently no default sorting is ever applied to the playlists because how would you know when to apply it? Tracks are added to a playlist through any manner of methods internal or external to the theme, and then grouped accordingly by the playlist manager in the theme. We can't apply a default sort at that point.

Correct me if I'm wrong, but I'm guessing your issue is that you've selected an album in the library, and then when you switch to the playlist then the order is all messed up, like so:

![image](https://user-images.githubusercontent.com/2282004/111685715-4092d000-87f6-11eb-8767-8d70f750805c.png)

What we can do is specify a default sort when creating playlists from the Library selection (similar to how the Hyperlinks playlist generation works). That is something that can and should be added to the config file.

For now you'll need to specify your sort manually in the right click Sort >> By... popup menu, and then manually apply it each time when the results are crappy.

**Comment by ghost** [comment]
> Correct me if I'm wrong, but I'm guessing your issue is that you've selected an album in the library, and then when you switch to the playlist then the order is all messed up

Yep, that is the case. Doesn't happen exactly the same as the image in your post, but yeah. Don't know if it's entirely necessary, but I suppose I'll attach some screenshots from my end for good measure.

With grouping query "album artist / album / discnumber" (one of the default included presets, left unchanged)
![album artist - album - discnumber](https://user-images.githubusercontent.com/62896596/111701070-a7bd7e00-8810-11eb-923f-6e1b496d0b81.PNG)

With grouping query "album artist / album / discnumber / labelno"
![album artist - album - discnumber - labelno](https://user-images.githubusercontent.com/62896596/111701092-af7d2280-8810-11eb-8541-d96b789631f8.PNG)

Thanks for the consideration, and keep up the good work!

**Comment by kbuffington** [comment]
So I started implementing this and discovered there is a way to control the sort for library stuff, but it kind of sucks currently. I'll be rewriting this, but maybe not in time for 2.0.2.

If you go to panel properties and scroll down you'll see this:
![image](https://user-images.githubusercontent.com/2282004/111729533-465fd400-883d-11eb-9866-b66f4f7d6a1c.png)

For View 2 that value is:
`View by Album Artist // %album artist%|%album%|[[%discnumber%.]%tracknumber%. ][%track artist% - ]%title%`

Everything before the // is the label in the menu. Everything after is the Library groupings including sort, divided by `|` to denote different levels.
So in that view setting, using your album, `%album artist%|` means the first level of the playlist will be "Morpheus Descends", then `%album%|` denotes the 2nd level will be Ritual of Gravity, and then the final level will be all songs displayed as `[[%discnumber%.]%tracknumber%. ][%track artist% - ]%title%`

What's unwritten, is that entire string is _ALSO_ the sort parameter. Which is why you're seeing the results you're seeing.

For now, the best/easiest thing for you to do would be to find whatever view you normally use in the Library Panel, and update the 2nd library tree level (which is usually `%album%|` and include whatever album delimiting field you'd like there; like this for example:

`%album%[ '['%edition%[ - %catalognumber%']']|` which would potentiall output something like "Ritual of Identity [Deluxe Edition - XM 032 CD]"

**Comment by ghost** [comment]
Oh, I see! I hadn't thought to check in that window and just assumed I should leave it alone, but I understand now.
I've modified preset 3 to my liking and put it in one of the three extra blank preset slots, and now I've got it how I wanted in the library view, which the auto/library playlist respects when I select tracks from the library, solving not only the problem I had with the library playlist but _also_ the incorrect displaying in the library view, which I had initially neglected to put much focus on.

This will do well in the meantime, thank you very much for the help!

![Capture](https://user-images.githubusercontent.com/62896596/111880903-5504d300-8984-11eb-89c7-c3b977b11cda.PNG)

**Comment by kbuffington** [comment]
@111mzd in 2.0.2 this behavior is changed (it will change again at some future point too, once patterns get added to the config file) and now the string is not used as a sort, and the `settings.defaultSortString` is what's used for hyperlinks or library selections being sent to the playlist.
