### ISSUE TITLE
Georgia 2.0.1 crashup start

### ISSUE THREAD

**Issue by silverwings15** [kbuffington/Georgia#88]
Another bug coming your way! Got the following error message when i booted up foobar after turning my laptop on. Reloading didn't help so i had to boot foobar in safe mode and reset the theme. I'll try to replicate this issue but seems unlikely, my only interaction with the volume bar was lowering the volume to about 70%
	
![image](https://user-images.githubusercontent.com/10742312/112086352-a1d3ee00-8bbe-11eb-978c-de3b66c34f84.png)

**Comment by kbuffington** [comment]
Try updating to the latest version of Georgia. I think that was fixed in 2.0.1. BTW, if you load the theme with no song playing do you see the notice about an available update?

Edit: actually that code update wasn't a part of 2.0.1, I did it a couple days later. Your title says 2.0.1, but your screenshot shows Georgia 2.0.0 is running. In the future if you get in a state where this is somehow happening with the volume button, you can disable it in the config file, then reload the theme, and your error should go away.

**Comment by silverwings15** [comment]
i'll keep that in mind. yeah i am using 2.0.1 (just downloaded the theme yesterday), don't know why SMP says 2.0.0

**Comment by kbuffington** [comment]
For now, you can clone the repo and see if the updated code doesn't eliminate that crash for you.

**Comment by silverwings15** [comment]
i've been unable to reproduce this so far, will reopen if i run into it again. thank you for the fix!
