### ISSUE TITLE
Library panel causing Georgia to crash

### ISSUE THREAD

**Issue by dwmartin0906** [kbuffington/Georgia#91]
Since applying your latest changes to Panel_Library.js I've started getting crashes.  I was performing searches at the time.  I've pasted the error message below.  Also, the search function is performing oddly.  I perform a search and that works fine.  But when I clear the search using the 'x' on the search bar it redisplays my search results when I expected it to redisplay the entire library.  What's odd is that it refreshes the counts to the right of the artist to reflect the total number of albums for each artist, but is still showing only the search results.  I will start using the playlist extensively without performing searches to see if I still get any crashes.

Error: Spider Monkey Panel v1.4.1 (Georgia: Georgia v2.0.2 by Mordred)
node is not defined

File: Panel_Library.js
Line: 1069, Column: 14
Stack trace:
  treeState@Panel_Library.js:1069:14
  on_metadb_changed@Panel_Library.js:3221:16
  on_metadb_changed@georgia-main.js:1684:12

**Comment by dwmartin0906** [comment]
The same error has occurred several more times.  The odd thing is that I had the library panel open, but wasn't doing anything, not even scrolling, when the error occurred.  I should mention that I've been testing with your version without any of my changes.

**Comment by kbuffington** [comment]
This stuff isn't quite ready for primetime. I'm majorly refactoring the library because it just shows (false errors) in my console and it's impossible to find anything or figure out what I'm doing.

![image](https://user-images.githubusercontent.com/2282004/113023532-5a63d980-914b-11eb-9749-db9bb4daf9be.png)

That number is down from 600+ errors when I started this fun. Lemme know if this doesn't fix it. I'm still doing extensive testing though so expect more things to break.
