### ISSUE TITLE
Album cover image became distorted

### ISSUE THREAD

**Issue by U118** [kbuffington/Georgia#92]
Hi there, 

It's my first time using foobar and I setup the georgia theme which is really great! When it was first installed, everything seemed fine but recently the album covers for a lot of albums look distorted when the image is definitely high-res. Even if I manually replace it through foobar with another high-res image, it still appears distorted. Could I have some help with this? Thanks a lot.

![image](https://user-images.githubusercontent.com/81634527/113005986-cfbeb280-9129-11eb-809c-15b321d2e05b.png)
![image](https://user-images.githubusercontent.com/81634527/113006060-dd743800-9129-11eb-868d-116a00b3cdd9.png)

**Comment by kbuffington** [comment]
This is caused by Windows Media Player (or some other Windows music player) downloading low res hidden artwork into the folders. If you show hidden files you'll see it. I'm finally fixing this so hidden artwork will not typically be displayed in this manner which should stop this support issue from coming up.

**Comment by U118** [comment]
Thanks for the explanation and for the quick response! Looking forward to the next update in the future and I'll be sure to uninstall other music players in case.
